import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import MessageCard from "../components/MessageCard/Index";
import SearchInput from "../components/SeachInput/Index";
import ConversationCountAndAddContact from "../components/ConversationCountAndAddContact/Index";
import ContactInfo from "../components/ConversionHeader/Index";
import Message from "../components/MessagesInConversation/Index";
import SendMessageInput from "../components/SendMessageInput/Index";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp By Julio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid lg:grid-cols-3">
        <div className="col-span-2 lg:col-span-1 border-r border-gray-300 lg:h-screen lg:overflow-y-scroll ">
          <ConversationCountAndAddContact />
          <SearchInput />
          <div className="">
            <MessageCard />
            <MessageCard />
            <MessageCard />
            <MessageCard />
            <MessageCard />
          </div>
        </div>
        <div className="hidden lg:col-span-2 w-full lg:flex lg:flex-col lg:justify-between lg:h-screen">
          <div className="border-b border-gray-300 w-full">
            <ContactInfo />
          </div>
          <div className="h-[60%] overflow-y-scroll grow p-3 flex flex-col gap-10">
            <Message />
            <Message />
            <Message />
            <Message />
            <Message />
          </div>
          <div className="p-3">
            <SendMessageInput />
          </div>
        </div>
      </main>
    </>
  );
}
