import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import MessageCard from "../components/MessageCard/Index";
import SearchInput from "../components/SeachInput/Index";
import ConversationCountAndAddContact from "../components/ConversationCountAndAddContact/Index";
import ContactInfo from "../components/ConversionHeader/Index";
import Message from "../components/MessagesInConversation/Index";
import SendMessageInput from "../components/SendMessageInput/Index";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp By Julio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ContactInfo />
        <ConversationCountAndAddContact />
        <SearchInput />
        <MessageCard />
        <Message />
        <SendMessageInput />
      </main>
    </>
  );
}
